env:
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended

plugins:
  - import

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  import/extensions:
    - error
    - ignorePackages
  import/no-commonjs:
    - error
